server:
  port: 8080

spring:
  application:
    name: amorepacific
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:amorepacific;DB_CLOSE_DELAY=-1
    username: root
    password: amorepacific2022!@
    initialization-mode: always
    data : file:src/main/resources/category.sql, file:src/main/resources/product.sql
  h2:
    console:
      enabled: true
      path: /h2
  devtools:
    livereload:
      enabled: false

logging:
  pattern:
    console: "%d{HH:mm} %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: INFO
    com: DEBUG